package pfa.alliance.fim.model.user;

/**
 * This enumeration contains all the existing permissions from the system.
 * 
 * @author Csaba
 */
public enum UserPermission
{
    PROJECT_CREATE_PROJECT,
    PROJECT_SHOW_PROJECT,
    PROJECT_EDIT_PROJECT,
    PROJECT_EDIT_PROJECT_ASSIGN_USER,
    PROJECT_EDIT_PROJECT_ASSIGN_PA,
    PROJECT_EDIT_PROJECT_ASSIGN_PO,
    PROJECT_EDIT_PROJECT_ASSIGN_SM,
    PROJECT_EDIT_PROJECT_CHANGE_OWNER,
    PROJECT_LIST_PROJECTS,
    PROJECT_SHOW_HIDDEN_PROJECTS,
    ADMIN_INVITE_USER,
    ADMIN_SEARCH_USERS,
    ADMIN_EDIT_OTHER_USER_PROFILE,
    ADMIN_MODIFY_USER_STATUS,
    ADMIN_RESET_USER_PASSWORD,
    ADMIN_SHOW_ASSIGNED_PROJECTS,

    ADMIN_SETTINGS,

    ISSUE_CRAETE_ISSUE,
    ISSUE_SHOW_ISSUE,
    ISSUE_EDIT_ISSUE,
}
